### ISSUE TITLE
Add zod to dependencies

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/js-docker-isolation-provider#36]

**Comment by konard** [comment]
@FreePhoenix888 do you mean https://github.com/colinhacks/zod ? How is it useful?

**Comment by FreePhoenix888** [comment]
> @FreePhoenix888 do you mean https://github.com/colinhacks/zod ? How is it useful?

@Konard why do you ask? I need it and I have added this issue to add it later

**Comment by konard** [comment]
@FreePhoenix888 I ask because I want to know about it. What you need it for?

**Comment by FreePhoenix888** [comment]
> @FreePhoenix888 I ask because I want to know about it. What you need it for?

You can read in their readme how useful that tool is. I will use it to validate value of a config link in npm2github package and in other packages later, this library is very usefull for me
